# Generated by Django 4.0.1 on 2022-02-12 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_purchase_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='products_purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockout', to='inventory.products_purchase'),
        ),
    ]
