# Generated by Django 4.0.1 on 2022-02-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stock_products_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_purchase',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
