# Generated by Django 4.0.1 on 2022-02-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_products_purchase_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_purchase',
            name='selling_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
